---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Get NDVI and NDBI around Cortisol Sampling Points

## Get libs

```{r}
# for data
library(readxl)
library(dplyr)
library(tidyr)
library(readr)
library(sf)
library(raster)
```

## Get data

```{r}
# path to data
cortisol_data = read_excel("data/raw/hair data.xlsx")

# get coordinates and id
cortisol_sf = st_as_sf(cortisol_data, coords = c("lon", "lat"),
                    crs = st_crs(4326))

# write to file
st_write(cortisol_sf, dsn = "data/spatial/data_cortisol_duke.gpkg")

# count unique coords
cortisol_sf_count = group_by(cortisol_data, lon, lat) %>% 
  count() %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = st_crs(4326))

# save
st_write(cortisol_sf_count, dsn = "data/spatial/data_cortisol_count_duke.gpkg")
```

## Make buffers

```{r}
# buffer size (in metres)
area = 40000 # 4 hectares
radius = sqrt(area / pi)

# transform and make buffer
cortisol_data_buffer = st_transform(cortisol_sf, crs = 32617) %>% 
  st_buffer(radius) %>% 
  st_transform(4326)

# export bounding box
cortisol_bbox = st_as_sfc(
  cortisol_data_buffer %>% 
    st_bbox()
)
st_write(cortisol_bbox, dsn = "data/spatial/data_cortisol_bbox.shp",
         append = F)
```

## Get NDVI and NDBI data

Refer to the `iPython` file for Google Earth Engine for GEE Python scripts.

```{r}
# get rasters
ndvi = raster("data/spatial/duke_ndvi_cortisol.tif")
ndbi = raster("data/spatial/duke_built_up_cortisol.tif")

# rescale built up
values(ndbi) = scales::rescale(values(ndbi))

# save raster
writeRaster(ndbi, filename = "data/spatial/duke_built_up_cortisol.tif",
            overwrite = T)
```

## Extract data

```{r}
# extract data
env_data = lapply(seq(nrow(cortisol_data_buffer)), function(r) {
  # extract data as matrix
  raster::extract(
    x = stack(ndvi, ndbi), 
    y = as(cortisol_data_buffer[r,], "Spatial"), 
    fun = function(x, na.rm) {
      v = round(
        c(mean = mean(x, na.rm = na.rm),
          median = median(x, na.rm = na.rm),
          sd = sd(x, na.rm = na.rm)),
        4)
    }) %>%
    # convert to data frame, add id, rename variables
    as_tibble(env_data, rownames = "metric") %>% 
    mutate(ID_hormone = cortisol_data_buffer$ID_hormone[r]) %>% 
    rename(ndvi = "duke_ndvi_cortisol",
           built_up = "duke_built_up_cortisol") %>% 
    # pivot wider
    pivot_wider(
      id_cols = ID_hormone,
      names_from = metric, 
      values_from = c("ndvi", "built_up")
    )
})

env_data = bind_rows(env_data)
```

## Join with sampling locations and save

```{r}
# join
cortisol_data = left_join(cortisol_data,
                          env_data,
                          by = "ID_hormone")

# save
write_csv(cortisol_data, "data/data_cortisol_environmental_data.csv")
```

