# -*- coding: utf-8 -*-
"""landcover_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cCrRU3eO1TuAQmtTYFxqPZyJeQZ1_9J
"""

!pip install -U -q git+https://github.com/mccarthyryanc/folium_gee.git

# Installs geemap package
import subprocess

try:
    import geemap
except ImportError:
    print('geemap package not installed. Installing ...')
    subprocess.check_call(["python", '-m', 'pip', 'install', 'geemap'])

# Checks whether this notebook is running on Google Colab
try:
    import google.colab
    import geemap.eefolium as geemap
except:
    import geemap

# Authenticates and initializes Earth Engine
import ee

try:
    ee.Initialize()
except Exception as e:
    ee.Authenticate()
    ee.Initialize()

# prelim code for earth engine landcover around duke

# get transects from user assets
transects = ee.FeatureCollection("users/pratik_unterwegs/squirrel_transects")

# get a 1km buffer
buffer_size_m = 90
transect_geom = transects.geometry()
transect_buffer = transect_geom.buffer(buffer_size_m)

# define start and end date
start_date = '2020-04-01'
end_date = '2020-10-01'

# filter sentinel by bounding box
# get sentinel data
sentinel = ee.ImageCollection("COPERNICUS/S2")
sentinel_bounds = sentinel.filterBounds(transect_buffer)
sentinel_2020 = sentinel_bounds.filterDate(start_date, end_date)

# print some information
count = sentinel_2020.size().getInfo()
print("Count: ", count)

# adding a NDVI band
def add_ndvi(image):
    ndvi = image.normalizedDifference(['B8', 'B4']).rename('ndvi')
    return image.addBands([ndvi])

# map ndvi over sentinel
sentinel_ndvi = sentinel_2019.map(add_ndvi)

# get median values
ndvi_median = sentinel_ndvi.select('ndvi').mean()

# clip to geometry
ndvi_clip = ndvi_median.clip(transect_buffer)

# Define an sld style color ramp to apply to the image.
sld_ramp = \
  '<RasterSymbolizer>' + \
    '<ColorMap type="ramp" extended="false" >' + \
      '<ColorMapEntry color="#0D0887" quantity="-0" label="0"/>' + \
      '<ColorMapEntry color="#5D01A6" quantity="0.1" label="100" />' + \
      '<ColorMapEntry color="#9C179E" quantity="0.25" label="200" />' + \
      '<ColorMapEntry color="#CC4678" quantity="0.35" label="300" />' + \
      '<ColorMapEntry color="#ED7953" quantity="0.45" label="400" />' + \
      '<ColorMapEntry color="#F0F921" quantity="0.55" label="500" />' + \
    '</ColorMap>' + \
  '</RasterSymbolizer>';

# print layers
vis = {'bands': ['ndvi']}
Map = geemap.Map(center=[36,-79], zoom=4)
Map.addLayer(ndvi_clip.sldStyle(sld_ramp), {}, 'ndvi')
Map.addLayer(transects)
Map.addLayerControl()
Map